image: docker-registry.lan.adytonsystems.com/node-4-phantomjs

variables:
  JSPM_GITHUB_AUTH_TOKEN: Z3BtaWtlcDpkNDYyZjc5OWU0ODAwYmI3MjAyZWRjM2ZhZWI2Yzg2MDZiNzg5MmM0

## per project/branch caching but not when building tags
cache:
  key: "$CI_PROJECT_ID/$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - jspm_packages/
    - typings/

# install environment && build app && test && generate index.html
build:
  tags:
    - docker
  artifacts:
    paths:
      - dist/index.html
  script:
    - npm install && npm run deps && npm run build && npm run package
